print("DGP 1 Running!")
print(Sys.time())
source("master_dgp1.R")
print(Sys.time())
print("DGP 2 Running!")
print(Sys.time())
source("master_dgp2.R")
print(Sys.time())
print("DGP 3 Running!")
print(Sys.time())
source("master_dgp3.R")
print(Sys.time())
print("DGP 4 Running!")
print(Sys.time())
source("master_dgp4.R")
print(Sys.time())